
steps:
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'timeless-appointment' # This will be your Cloud Run service name
      - '--source'
      - '.' # Deploy from the current directory
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - 'timeless-appointment' # Your Google Cloud Project ID
      # Cloud Build will use buildpacks to build the Node.js application.
      # The entrypoint will be taken from the "start" script in package.json.
      # To specify a Node.js version for buildpacks if needed:
      # - '--set-env-vars=GOOGLE_NODE_VERSION=20'
    id: 'Deploy to Cloud Run'

# Optional: specify timeout for the build
timeout: '1200s' # 20 minutes

# Optional: specify images to be pushed to Artifact Registry or Container Registry
# By default, Cloud Run source deployments build and push an image for you.
# images:
#  - 'us-central1-docker.pkg.dev/timeless-appointment/cloud-run-source-deploy/timeless-appointment:$COMMIT_SHA'
#  - 'us-central1-docker.pkg.dev/timeless-appointment/cloud-run-source-deploy/timeless-appointment:latest'
